name = "StateSpaceSciML"
uuid = "4a83fda9-5f8e-4d95-a8ed-6b3245da5831"
authors = ["Jack Buckner <bucknejo@oregonstate.edu>"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
